### ISSUE TITLE
Patterns containing /**/ don't work properly

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-config-aggregator#1]
Patterns using /**/ do not recursively match sub directories and instead stop at the current depth.  This seems to be a limitation of the php glob function but I think this would be a nice feature to have.

---

Originally posted by @marcelto at https://github.com/zendframework/zend-config-aggregator/issues/10

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
