### ISSUE TITLE
Upgrade 1.1.1 to 1.2.0 break caching feature

### ISSUE THREAD

**Issue by dominicdettabp** [laminas/laminas-config-aggregator#2]
### BC Break Report

After running the application on Windows.
```
PHP Warning:  rename(C:\Users\****\AppData\Local\Temp\2\test.php.tmp,test.php): Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (code: 32) in D:\Apache_idpm\htdocs\test-config-cache.php on line 18

Warning: rename(C:\Users\****\AppData\Local\Temp\2\test.php.tmp,test.php): Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (code: 32) in D:\Apache_idpm\htdocs\test-config-cache.php on line 18
```

|    Q        |   A
|------------ | ------
| laminas-config-aggregator     |1.2.0
| PHP CGI/Fast-CGI     |7.2.23
| Apache     | 2.4
| Windows     | Windows Server 2016

#### Summary

When executing any scripts or running the application the error above appears.
It seems that the function `ConfigAggregator::cacheConfig` generate a file in the `sys_temp_dir` and then try to rename the source file to the desired filename.

I tried to check if a process where using the source file with the service `Process explorer` but no results found.

#### Previous behavior

The file `config-cache.php` is generated in the `data` folder.

#### Current behavior

No file `config-cache.php` is generated and the error above appears.

#### How to reproduce

The `sys_temp_dir` is default to `C:\Users\****\AppData\Local\Temp`
This is a simple php script to reproduce the behaviour on Windows.
```
$cachedConfigFile='test.php';
$tempFile=sys_get_temp_dir() . DIRECTORY_SEPARATOR . basename($cachedConfigFile) . '.tmp';
$fh = fopen($tempFile, 'c');
//chmod($tempFile, '0777');
ftruncate($fh, 0);
fputs($fh,'test');
rename($tempFile, $cachedConfigFile);
fclose($fh);
```

**Comment by kynx** [comment]
@dominicdettabp This was almost certainly caused by https://github.com/zendframework/zend-config-aggregator/pull/23

I don't have (easy) access to a Windows machine, but I suspect Windows doesn't like the `rename()` coming before the `fclose()`.

Does your test script work if you replace the `rename()` line with:

```
copy($tempFile, $cachedConfigFile);
unlink($tempFile);
```

Cheers.

**Comment by dominicdettabp** [comment]
Another error appears: 
``
PHP Warning:  unlink(C:\Users\****\AppData\Local\Temp\3\test.php.tmp): Resource temporarily unavailable in D:\Apache
_idpm\htdocs\test.php on line 9

Warning: unlink(C:\Users\****\AppData\Local\Temp\3\test.php.tmp): Resource temporarily unavailable in D:\Apache_idpm
\htdocs\test.php on line 9
``

**Comment by kynx** [comment]
So maybe:

```
copy($tempFile, $cachedConfigFile);
fclose($fh);
unlink($tempFile);
```

(`fclose()` will release the lock, so has to happen after the `copy()`)

**Comment by dominicdettabp** [comment]
@kynx it works! 
Right now we are using the old `zendframework/zend-config-aggregator.
Is it possible to add a patch directly on the old repository or I must migrate to the new Laminas namespace?

**Comment by dominicdettabp** [comment]
@kynx  FYI, the code: 
``
<?php
$cachedConfigFile='test.php';
$tempFile=sys_get_temp_dir() . DIRECTORY_SEPARATOR . basename($cachedConfigFile) . '.tmp';
$fh = fopen($tempFile, 'c');
if (! $fh) {
    return;
}
if (! flock($fh, LOCK_EX | LOCK_NB)) {
    fclose($fh);
    return;
}
//chmod($tempFile, '0777');
ftruncate($fh, 0);
fputs($fh,'test');
copy($tempFile, $cachedConfigFile);
flock($fh, LOCK_UN);
fclose($fh);
unlink($tempFile);
``

**Comment by kynx** [comment]
@dominicdettabp Good to hear.

All the old `zend-config-aggregator` tags are available in the laminas version - I'd just lock to the previous version in composer.json until a fix is released to this repo:

```
"laminas/laminas-config-aggregator": "1.1.1",
```
