### ISSUE TITLE
Validation for `class-string` config providers to be unique

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-config-aggregator#36]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I recently detected some duplicate entries within the config provider array which is passed to the `ConfigAggregator#__construct`. Since it requires the config to be merged multiple times while it makes no sense, I'd say we could add some validation to the `ConfigAggregator#__construct` to at least report duplicated `class-string` and/or `function-string` values.

WDYT?

**Comment by Ocramius** [comment]
The description seems sensible, but I don't have an example in mind? 🤔

**Comment by boesing** [comment]
Due to `laminas-component-installer`, merge-conflicts, etc. it might happen that you end up with more than one entry of the same config provider.

We do have a quite large `ConfigAggregator` which is aggregating 100+ configs. *Sometimes* we end up having the same config loaded multiple times which can, i.e. when the order is mandatory (due to dependency overrides, etc.), lead to annoying issues.

I am aware that raising the attention for having two configs loaded twice does not directly hint some1 to that problem itself but I'd expect that once issues occur after release (i.e. due to the fact that services are not replaced anymore) some1 at least can relate that most-recently the config aggregator aggregated the same component twice and most probably one deleted the wrong one.


Example would be:

```php
$config = new ConfigAggregator([
    Foo::class, // introduces service interface XY
    Bar::class, // overrides service interface XY with whatever
    Foo::class, // overrides service interface XY with whatever back to the initial service
]);
```

So this is super obvious in projects with 5 config providers but once there are 100+, this is not that obvious if there are a bunch of other providers in between.

**Comment by Xerkus** [comment]
Should config aggregator fail when duplicate entries are detected and prevent application from starting?

Most likely outcome of duplicate entries is merely some merge overhead before config is cached. It can be potentially surprising if merge order matters but I would rate it as fairly unlikely for already fairly rare occurrence.

**Comment by boesing** [comment]
I'd say let it crash. There is no good other way to provide that information to application owner outside of having it crashing.
Duplication check shouldn't be applied when config is cached.

Mark that behavior in the release notes, IMHO good enough.
